version: '3.8'

services:
  trading-bot:
    build: .
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SIGNAL_PROCESSOR_URL=http://tradingview-signal-matcher:5000
      - SIGNAL_AI_SERVICE_URL=http://tradingview-signal-ai-service:5000
      - CHART_SERVICE_URL=http://tradingview-chart-service:5000
      - NEWS_SERVICE_URL=http://tradingview-news-ai-service:5000
      - CALENDAR_SERVICE_URL=http://tradingview-calendar-service:5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
    depends_on:
      - redis
      - tradingview-signal-matcher
      - tradingview-signal-ai-service
      - tradingview-news-ai-service
      - tradingview-chart-service
      - tradingview-calendar-service
    volumes:
      - ./logs:/app/logs

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  tradingview-signal-matcher:
    build: ./tradingview-signal-matcher
    environment:
      - REDIS_HOST=redis
      - PORT=5000
      - SIGNAL_AI_SERVICE_URL=http://tradingview-signal-ai-service:5000
      - CHART_SERVICE_URL=http://tradingview-chart-service:5000
      - NEWS_SERVICE_URL=http://tradingview-news-ai-service:5000
      - CALENDAR_SERVICE_URL=http://tradingview-calendar-service:5000
    depends_on:
      - redis
      - tradingview-signal-ai-service
      - tradingview-news-ai-service
      - tradingview-chart-service
      - tradingview-calendar-service

  tradingview-signal-ai-service:
    build: ./tradingview-signal-ai-service
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
      - PORT=5000
    depends_on:
      - redis

  tradingview-news-ai-service:
    build: ./tradingview-news-ai-service
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=redis
      - PORT=5000
    depends_on:
      - redis

  tradingview-chart-service:
    build: ./tradingview-chart-service
    environment:
      - REDIS_HOST=redis
      - PORT=5000
    depends_on:
      - redis

  tradingview-calendar-service:
    build: ./tradingview-calendar-service
    environment:
      - REDIS_HOST=redis
      - PORT=5000
    depends_on:
      - redis

  telegram-service:
    build: ./tradingview-telegram-service
    environment:
      - SIGNAL_PROCESSOR_URL=http://tradingview-signal-matcher:5000
      - SIGNAL_AI_SERVICE_URL=http://tradingview-signal-ai-service:5000
      - CHART_SERVICE_URL=http://tradingview-chart-service:5000
      - NEWS_SERVICE_URL=http://tradingview-news-ai-service:5000
      - CALENDAR_SERVICE_URL=http://tradingview-calendar-service:5000
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - REDIS_HOST=redis
      - PORT=5000
    depends_on:
      - redis
      - tradingview-signal-matcher
      - tradingview-signal-ai-service
      - tradingview-news-ai-service
      - tradingview-chart-service
      - tradingview-calendar-service 