version: '3.8'
services:
  trading-bot:
    build: .
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SIGNAL_PROCESSOR_URL=http://tradingview-signal-matcher:5000
      - SIGNAL_AI_SERVICE_URL=http://tradingview-signal-ai-service:5000
      - CHART_SERVICE_URL=http://tradingview-chart-service:5000
      - NEWS_SERVICE_URL=http://tradingview-news-ai-service:5000
      - CALENDAR_SERVICE_URL=http://tradingview-calendar-service:5000
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=5000
    depends_on:
      - redis

  tradingview-signal-matcher:
    build: ./tradingview-signal-matcher
    environment:
      - REDIS_HOST=redis
      - PORT=5000
      - SIGNAL_AI_SERVICE_URL=http://tradingview-signal-ai-service:5000
      - NEWS_SERVICE_URL=http://tradingview-news-ai-service:5000
      - CHART_SERVICE_URL=http://tradingview-chart-service:5000
      - TELEGRAM_SERVICE_URL=http://tradingview-telegram-service:5000
    networks:
      - tradingview-network
    depends_on:
      - redis
      - tradingview-chart-service
      - tradingview-telegram-service

  tradingview-signal-ai-service:
    build:
      context: ./tradingview-signal-ai-service
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - TELEGRAM_SERVICE_URL=http://tradingview-telegram-service:5000
      - CHART_SERVICE_URL=http://tradingview-chart-service:5000
    volumes:
      - ./tradingview-signal-ai-service:/app
      - /app/node_modules
    networks:
      - tradingview-network

  tradingview-news-ai-service:
    build:
      context: ./tradingview-news-ai-service
      dockerfile: Dockerfile
    ports:
      - "5002:5000"
    environment:
      - PORT=5000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./tradingview-news-ai-service:/app
    networks:
      - tradingview-network

  tradingview-chart-service:
    build:
      context: ./tradingview-chart-service
      dockerfile: Dockerfile
    ports:
      - "5007:5000"
    environment:
      - PORT=5000
    volumes:
      - ./tradingview-chart-service:/app
    networks:
      - tradingview-network

  tradingview-telegram-service:
    build: ./tradingview-telegram-service
    env_file:
      - .env
    environment:
      - TELEGRAM_BOT_TOKEN=7583525993:AAFh8WhxsHkQD9BD7VertRauNYkJbstN8wI
    ports:
      - "5000:5000"
    container_name: tradingview-telegram-service
    networks:
      - tradingview-network
    depends_on:
      - redis
      - tradingview-news-ai-service
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - tradingview-network

  tradingview-calendar-service:
    build: 
      context: ./tradingview-calendar-service
      dockerfile: Dockerfile
    ports:
      - "5003:5000"
    environment:
      - REDIS_HOST=redis
      - TELEGRAM_SERVICE_URL=http://tradingview-telegram-service:5000
    depends_on:
      - redis
      - tradingview-telegram-service
    networks:
      - tradingview-network

networks:
  tradingview-network:
    driver: bridge
