[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
restartPolicyType = "on_failure"
healthcheckPath = "/health"
healthcheckTimeout = 10

[http]
internal_port = 8080
external_port = 443